### ISSUE TITLE
Ship landing in wrong spot?

### ISSUE THREAD

**Issue by ChooMcoo** [BoniatoRelleno/Ganimedes#1]
![image](https://github.com/BoniatoRelleno/Ganimedes/assets/155716855/9b1fc4e3-f2a9-4d65-80c7-b902db0be458)

I'm assuming it should be landing in the marked area and not right by the entrance lol. Also you should join the Lethal Company Modding DIscord and post your mod in a forum so you can talk with people and people can follow your mod easier! I typically try to convince folks to join because its convenient and there are plenty of other moon devs you can get help from and bounce ideas between.

**Comment by ChooMcoo** [comment]
Forgot to post the invite in case you're interested lol https://discord.com/invite/lcmod

**Comment by BoniatoRelleno** [comment]
Hi! First of all, thanks for have played my mod! That spot was used to land ships when the mine was active but now it is abandoned and you can land wherever you want, it isn't a bug.

Oh, thanks for your advices, it's my first mod, so I didn't know that forum. I will join to the discord :)

**Comment by ChooMcoo** [comment]
![image](https://github.com/BoniatoRelleno/Ganimedes/assets/155716855/d80fbc67-3cc6-421e-aa7f-7f4cf32ffb67)
You can post your moon under the mod-releases forum area!

**Comment by BoniatoRelleno** [comment]
Yeah, I'm thinking about waiting until tomorrow to publish a post with well-made photos of the moon

**Comment by ChooMcoo** [comment]
Sure thing! Looking forward to seeing your post :)
