### ISSUE TITLE
document "internal name"

### ISSUE THREAD

**Issue by nephatrine** [BoniatoRelleno/Ganimedes#2]
Some interior dungen mods require the specific "internal name" of the level be specified if assigning spawn chances. For the vanilla levels these are things like `DineLevel` and `ExperimentationLevel` rather than the normal name of the moon. Some moon mods such as Atlas Abyss and Secret Labs explicitly specify their internal name in the readme for this purpose. I cannot find any such documentation for Ganimedes. Is the internal moon name just `Ganimedes` or maybe it is `GanimedesLevel` or maybe something else? It would be nice to just have it explicitly stated on in the readme so there's no guessing games needed.

**Comment by BoniatoRelleno** [comment]
Hi! With just `Ganimedes` it should be fine. Thanks for the suggestion! I will add it to the readme :)
