### ISSUE TITLE
Low FPS 

### ISSUE THREAD

**Issue by BAHEK-BOP** [BoniatoRelleno/Ganimedes#3]
Please, dude, your map is amazing, but my fps drops, sometimes up to 30-40 frames

Please correct this in a future update, and the question is, will you make more new maps?

**Comment by BoniatoRelleno** [comment]
Hi, I'm glad you like the map! 

Unfortunately, there's not much I can do about the fps drops, I'll try to optimize the map as much as possible in the future, but I still have a lot of things to do. 

In answer to your question, yes, I already have the idea for another moon but I don't think I will do it until I finish adding everything I have in mind for Ganimedes. A small advance is that it will be a free moon, more difficult and profitable than the intermediate ones and with an environment that no other moon has been done so far (I hope they don't get ahead of me).
