### ISSUE TITLE
[Question] can i ask, the pickaxe that including in this mod have their own RPC?

### ISSUE THREAD

**Issue by CoolLKKPS** [BoniatoRelleno/Ganimedes#8]
@BoniatoRelleno there's a mod call AntiCheat, that mod using call shovel RPC to prevent player dealing more damage, does the pickaxe from this mod are also using shovel RPC?

**Comment by BoniatoRelleno** [comment]
Yes, it uses the same RPC, it is a shovel but with double the damage

**Comment by CoolLKKPS** [comment]
ok, thx, AntiCheat author tell me mod item won't be affect unless they used the shovel rpc, the reason why i have this question. btw make own rpc if u can, will be grateful
